# HOW TO SET UP GMAIL:
# 1. Enable 2-factor authentication on your Google account
# 2. Go to: Google Account -> Security -> App Passwords
# 3. Create an app password for "Mail"
# 4. Paste the 16-character password into $AppPassword below
# 5. Set $FromEmail and $ToEmail to your Gmail address

param(
  [string]$Month = "",
  [switch]$DryRun,
  [switch]$LastDayOfMonth
)

$ProjectRoot = Split-Path $PSScriptRoot -Parent
Set-Location $ProjectRoot

if ($LastDayOfMonth) {
  $d = Get-Date
  if ($d.Day -ne [DateTime]::DaysInMonth($d.Year, $d.Month)) {
    exit 0
  }
}

# Config — user fills these in
$SmtpServer   = "smtp.gmail.com"
$SmtpPort     = 587
$FromEmail    = "your@gmail.com"
$ToEmail      = "your@gmail.com"
$AppPassword  = "your-app-password"   # Gmail app password

# If no month passed, use last month
if (-not $Month) {
  $date  = (Get-Date).AddMonths(-1)
  $Month = $date.ToString("yyyy-MM")
}

$MonthLabel = [datetime]::ParseExact($Month, "yyyy-MM", $null).ToString("MMMM yyyy")

# Step 1: Run the monthly summary script and capture output
Write-Host "Generating summary for $MonthLabel..."
$summary = & node "scripts/monthly-summary.mjs" $Month 2>&1 |
  Where-Object { $_ -notmatch "Breadcrumb|Syncing|Got messages|Closing" }

# Step 2: Find most recent budget plan
$planFile = Get-ChildItem (Join-Path $ProjectRoot "summaries\budget-plan-*.md") -ErrorAction SilentlyContinue |
  Sort-Object LastWriteTime -Descending |
  Select-Object -First 1

$planSection = ""
if ($planFile) {
  $planSection = @"
<h2>Latest budget export</h2>
<p><strong>$($planFile.Name)</strong> (under summaries\)</p>
"@
}

# Step 3: Build HTML email body
$html = @"
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333; }
  h1 { color: #2c5282; border-bottom: 2px solid #2c5282; padding-bottom: 8px; }
  h2 { color: #2d3748; margin-top: 24px; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th { background: #2c5282; color: white; padding: 8px 12px; text-align: left; }
  td { padding: 8px 12px; border-bottom: 1px solid #e2e8f0; }
  tr:nth-child(even) { background: #f7fafc; }
  .over  { color: #e53e3e; font-weight: bold; }
  .under { color: #38a169; font-weight: bold; }
  .warn  { color: #d69e2e; font-weight: bold; }
  .summary-box { background: #ebf8ff; border-left: 4px solid #2c5282;
                 padding: 12px 16px; margin: 16px 0; border-radius: 4px; }
  .footer { color: #718096; font-size: 12px; margin-top: 32px;
            border-top: 1px solid #e2e8f0; padding-top: 12px; }
</style>
</head>
<body>
<h1>Monthly Budget Report: $MonthLabel</h1>

<div class="summary-box">
<strong>Generated by your local Actual Budget + Ollama pipeline</strong><br>
All data pulled directly from Actual Budget. No cloud services used.
</div>

<h2>AI Summary</h2>
<pre style="white-space: pre-wrap; font-family: Arial; font-size: 14px;">
$($summary -join [Environment]::NewLine)
</pre>

$planSection

<h2>Next Steps</h2>
<ul>
  <li>Run <code>npm run tracker</code> to check current month progress</li>
  <li>Run <code>npm run ideate:export</code> to generate next month budget</li>
  <li>Run <code>.\run-categorizer.ps1</code> to categorize new transactions</li>
</ul>

<div class="footer">
  Sent automatically by actualbudget-autocategorize<br>
  Report date: $(Get-Date -Format 'yyyy-MM-dd HH:mm')
</div>
</body>
</html>
"@

# Step 4: Send or print
if ($DryRun) {
  Write-Host "=== DRY RUN - Email not sent ===" -ForegroundColor Yellow
  Write-Host "To:      $ToEmail"
  Write-Host "Subject: Monthly Budget Report: $MonthLabel"
  Write-Host "Body preview (first 500 chars):"
  Write-Host ($html.Substring(0, [Math]::Min(500, $html.Length)))
} else {
  Write-Host "Sending email to $ToEmail..." -ForegroundColor Yellow

  $secure = ConvertTo-SecureString $AppPassword -AsPlainText -Force
  $credential = New-Object System.Management.Automation.PSCredential($FromEmail, $secure)

  Send-MailMessage `
    -From $FromEmail `
    -To $ToEmail `
    -Subject "Monthly Budget Report: $MonthLabel" `
    -Body $html `
    -BodyAsHtml `
    -SmtpServer $SmtpServer `
    -Port $SmtpPort `
    -UseSsl `
    -Credential $credential

  Write-Host "Email sent successfully" -ForegroundColor Green
}
